### ISSUE TITLE
User Analytics

### ISSUE THREAD

**Issue by gentrexha** [cowprotocol/data-misc#11]

**Comment by bh2smith** [comment]
What is this?

**Comment by gentrexha** [comment]
> What is this?

I wanted to start using Projects to start managing some of the stuff we are working on. This would be an epic regarding User Analytics, where I could dump all the feedback/stuff I have about it and create separate tickets about individual tasks from here.

I believe Alex has already mentioned this to you regarding the ZenHub board he created.

What do you think?

**Comment by gentrexha** [comment]
I now realized that this repo is public, and probably shouldn't be. I was thinking maybe we could create a separate private repo for that?

**Comment by bh2smith** [comment]
We have a private repo for data stuff and it's called cow dune. This repo was created to keep our public miscellaneous data stuff and I have slowly been moving public things out of cow dune to this one. The names don't make sense because cow dune used to be the public one.
