### ISSUE TITLE
Object Serialization

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/data-misc#20]
Might wanna look into https://marshmallow.readthedocs.io/en/stable/ for easier object serialization/deserialization . What's your take on that?

_Originally posted by @gentrexha in https://github.com/cowprotocol/data-misc/pull/15#discussion_r999303535_

**Comment by gentrexha** [comment]
I think that's a great idea!

**Comment by bh2smith** [comment]
Feel free to demonstrate if you like!

**Comment by gentrexha** [comment]
I might give this a go on Friday!

**Comment by gentrexha** [comment]
Successfully suggested and implemented Object serialization/deserialization with marshmallow. #21
